apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-config.fullname" . }}-config
  labels:
    {{- include "aws-config.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.aws.region }}
  AWS_OUTPUT: {{ .Values.aws.output }}
