apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-config.fullname" . }}
  labels:
    {{- include "aws-config.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "aws-config.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aws-config.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "aws-config.fullname" . }}-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "aws-config.fullname" . }}-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: {{ include "aws-config.fullname" . }}-config
              key: AWS_REGION
        - name: AWS_OUTPUT
          valueFrom:
            configMapKeyRef:
              name: {{ include "aws-config.fullname" . }}-config
              key: AWS_OUTPUT
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
